version: '3.8'

services:
  backend:
    image: backend-image
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"  # Exposing port 5001
    environment:
      - FLASK_APP=backend.py
      - FLASK_ENV=production
      - PORT=5001  # Set the port to 5001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_SEARCH_SERVICE_NAME=${AZURE_SEARCH_SERVICE_NAME}
      - AZURE_SEARCH_ADMIN_KEY=${AZURE_SEARCH_ADMIN_KEY}
      - AZURE_SEARCH_INDEX_NAME=${AZURE_SEARCH_INDEX_NAME}
    volumes:
      - .:/app
    networks:
      - my_network

  frontend:
    image: frontend-image
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5001  # Updated to point to port 5001
    volumes:
      - .:/app
      - ./.streamlit:/root/.streamlit
    command: ["streamlit", "run", "app.py"]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
