# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.frontend.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.frontend.txt

# Copy the rest of the application
COPY . .

# Copy the secrets file
COPY .streamlit/secrets.toml /root/.streamlit/secrets.toml

# Expose the Streamlit port
EXPOSE 8501

# Run the Streamlit app
CMD ["streamlit", "run", "app.py"]